# Generated by Django 4.1 on 2022-08-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameSmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsmi', models.CharField(max_length=55, verbose_name='Наименование СМИ')),
            ],
            options={
                'verbose_name': 'Наименование СМИ',
                'verbose_name_plural': 'Наименования СМИ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otdel', models.CharField(max_length=55, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemaPublik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temapublik', models.CharField(max_length=55, verbose_name='Тема публикаций')),
            ],
            options={
                'verbose_name': 'Тема публикаций',
                'verbose_name_plural': 'Темы публикаций',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TonPublik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonpublik', models.CharField(max_length=55, verbose_name='Тон публикации')),
            ],
            options={
                'verbose_name': 'Тон публикации',
                'verbose_name_plural': 'Тон публикаций',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VidMeropriyatia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidmeropriyatia', models.CharField(max_length=55, verbose_name='Вид мероприятия')),
            ],
            options={
                'verbose_name': 'Вид мероприятия',
                'verbose_name_plural': 'Виды мероприятий',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VidPublik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidpublik', models.CharField(max_length=55, verbose_name='Вид публикации')),
            ],
            options={
                'verbose_name': 'Вид публикации',
                'verbose_name_plural': 'Виды публикаций',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VidReklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidreklama', models.CharField(max_length=55, verbose_name='Вид рекламы')),
            ],
            options={
                'verbose_name': 'Вид рекламы',
                'verbose_name_plural': 'Вид реклам',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VidSmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsmi', models.CharField(max_length=55, verbose_name='Вид СМИ')),
            ],
            options={
                'verbose_name': 'Вид СМИ',
                'verbose_name_plural': 'Виды СМИ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SmiOtdels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_smiotdel', models.DateField(verbose_name='Дата мероприятия')),
                ('otdel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.otdel', verbose_name='Отдел')),
                ('temapublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.temapublik', verbose_name='Тематика публикации')),
                ('vidmeropriyatia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.vidmeropriyatia', verbose_name='Вид мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие СМИ',
                'verbose_name_plural': 'Мероприятия СМИ по отделам',
                'ordering': ['date_smiotdel'],
            },
        ),
        migrations.CreateModel(
            name='ReklamaSmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reklama', models.DateField(verbose_name='Дата рекламы')),
                ('kolvareklama', models.IntegerField(blank=True, null=True, verbose_name='Кол-во рекламы')),
                ('temapublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.temapublik', verbose_name='Тематика публикации')),
                ('vidreklama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.vidreklama', verbose_name='Вид рекламы')),
            ],
            options={
                'verbose_name': 'Реклама СМИ',
                'verbose_name_plural': 'Реклама в СМИ',
                'ordering': ['date_reklama'],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_press', models.TextField(blank=True, null=True, verbose_name='Название пресс-релиза')),
                ('date_press', models.DateField(verbose_name='Дата пресс-релиза')),
                ('temapublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.temapublik', verbose_name='Тематика публикации')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
                'ordering': ['date_press'],
            },
        ),
        migrations.CreateModel(
            name='GurnalSocNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_publiksn', models.TextField(blank=True, null=True, verbose_name='Название публикации')),
                ('date_publiksn', models.DateField(verbose_name='Дата публикации')),
                ('url_publiksn', models.URLField(verbose_name='Ссылка на публикацию')),
                ('nsmi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.namesmi', verbose_name='Название СМИ')),
                ('temapublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.temapublik', verbose_name='Тематика публикации')),
                ('tonpublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.tonpublik', verbose_name='Вид публикации')),
                ('vidpublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.vidpublik', verbose_name='Вид публикации')),
                ('vsmi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.vidsmi', verbose_name='Вид СМИ')),
            ],
            options={
                'verbose_name': 'Публикация в Соц. сетях',
                'verbose_name_plural': 'Публикации в Соц. сетях',
                'ordering': ['date_publiksn'],
            },
        ),
        migrations.CreateModel(
            name='GurnalSmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_publik', models.TextField(blank=True, null=True, verbose_name='Название публикации')),
                ('date_publik', models.DateField(verbose_name='Дата публикации')),
                ('url_publik', models.URLField(verbose_name='Ссылка на публикацию')),
                ('nsmi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.namesmi', verbose_name='Название СМИ')),
                ('temapublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.temapublik', verbose_name='Тематика публикации')),
                ('tonpublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.tonpublik', verbose_name='Вид публикации')),
                ('vidpublik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.vidpublik', verbose_name='Вид публикации')),
                ('vsmi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smi2022.vidsmi', verbose_name='Вид СМИ')),
            ],
            options={
                'verbose_name': 'Публикация СМИ',
                'verbose_name_plural': 'Публикации в СМИ',
                'ordering': ['date_publik'],
            },
        ),
    ]
