# Generated by Django 4.1 on 2022-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smi2022', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otdel',
            name='kontrol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контрольная цифрв'),
        ),
    ]
