# Generated by Django 4.1 on 2022-08-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smi2022', '0002_otdel_kontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdel',
            name='kontrol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контрольная цифра'),
        ),
        migrations.AlterField(
            model_name='temapublik',
            name='temapublik',
            field=models.CharField(max_length=85, verbose_name='Тема публикаций'),
        ),
    ]
